# Generated by Django 3.2.8 on 2021-11-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_example', '0002_rename_user_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
