# Generated by Django 3.2.8 on 2021-12-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_example', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
